# Generated by Django 3.2.5 on 2021-07-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0003_auto_20210715_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('國文', '國文'), ('數學', '數學'), ('英文', '英文'), ('自然', '自然'), ('社會', '社會'), ('技術', '技術')], default='請選擇科目', max_length=10, verbose_name='科目')),
                ('name', models.CharField(max_length=20, verbose_name='課程名稱')),
                ('descritions', models.CharField(max_length=5000, verbose_name='介紹')),
                ('image', models.ImageField(upload_to='picture/%Y/%m/%d/', verbose_name='課程封面')),
                ('lessons', models.IntegerField(verbose_name='課堂數')),
                ('cost', models.IntegerField(verbose_name='T幣')),
                ('student', models.ManyToManyField(default='學生', to='personal.Student')),
                ('teacher', models.ForeignKey(default='教師', on_delete=django.db.models.deletion.CASCADE, to='personal.teacher')),
            ],
        ),
    ]
