# Generated by Django 3.2.5 on 2021-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20210715_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coin',
            field=models.IntegerField(default=None, verbose_name='T幣數'),
        ),
    ]
