# Generated by Django 3.2.5 on 2021-07-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_student_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='coin',
            field=models.IntegerField(default=0, verbose_name='T幣數'),
        ),
    ]
