# Generated by Django 3.2.5 on 2021-07-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20210715_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin',
            field=models.IntegerField(verbose_name='T幣數'),
        ),
    ]
