# Generated by Django 3.2.5 on 2021-07-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_alter_coin_coin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
